### ISSUE TITLE
Estimation du nombre: pb de rafraichissement du formulaire

### ISSUE THREAD

**Issue by camillecarrier** [alexandresoro/ouca#1220]
-  Modifier une estimation du nombre -> inverser la valeur de indénombrable 
- Sauvegarder
- Cliquer sur modifier -> la valeur d'indénombrable affichée est toujours l'ancienne valeur

- Modifier le nom d'un estimation du nombre (ou autre entité)
- Sauvegarder
- Cliquer sur modifier -> l'ancienne valeur apparait dans le formulaire et on ne peut pas sauvegarder le formulaire. Par contre si on remet la valeur actuelle on peut sauvegarder.

**Comment by alexandresoro** [comment]
Confirmed. This happens because the xxxUpdate page reuses the cached query.
Setting `cacheTime` to `0` does seem to fix the issue, however I see possible pitfalls as this is not a clean way: https://github.com/TanStack/query/discussions/2398

I'll replace that with simple `useApiFetch` that make sure to have up-to-date data.
Need to think about using raw `useApiFetch` or wrap every one of them per entity, but technically speaking, this will fix the issue anyway.
